Debugging value bump name check

diff --git a/.github/workflows/deploy-test.yml b/.github/workflows/deploy-test.yml
--- a/.github/workflows/deploy-test.yml
+++ b/.github/workflows/deploy-test.yml
@@ -16,8 +16,8 @@ jobs:
         if: github.event.inputs.version != 'patch' ||
           github.event.inputs.version != 'minor' ||
           github.event.inputs.version != 'major'
-        run: echo "::error The version bump argument was not valid. Value should be 'patch', 'minor' or 'major'." && exit 1
-      
+        run: echo "::error The version bump argument was not valid. Value should be 'patch', 'minor' or 'major' when the value received was ${{ github.event.inputs.version }}." && exit 1
+
       - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
